# Generated by Django 4.2.1 on 2023-05-09 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='section',
            field=models.CharField(default='default section', max_length=50, verbose_name='Раздел'),
            preserve_default=False,
        ),
    ]
